stages :
    - env        
env :
    stage : env
    script :
        - echo $PWD
        - ls
        - myvar="$PWD"
        - cd "$myvar"
        - chmod 777 -R ./
        - chmod 777 *
        - npm install --save-dev  --unsafe-perm node-sass
        - npm install angular2-cookie
        - npm install file-saver
        - npm install xlsx
        # - npm i @stomp/ng2-stompjs
        - ng build
        - aws configure set aws_access_key_id $AWS_ACCESS_KEY
        - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        - aws configure set region ap-northeast-1
        - aws s3 cp dist/smartadmin-angular-seed s3://config.advait-2.5.net --recursive --acl public-read
